services:
  - type: web
    name: app-gastos
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
